name: Docker Scout Vulnerability Scan

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Scout (v1.16.1)
        run: |
          # Download and install Docker Scout using the official installation script
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          

      - name: Pull and Scan Docker Image for CVEs
        run: |
          # Run the docker scout cves command to display CVEs in the image
          docker scout cves nginx:latest > scan-results.txt

      - name: Upload Scan Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-scan-results
          path: scan-results.txt
