name: Docker Scout Vulnerability Scan

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Scout (v1.16.1)
        run: |
          # Create the directory if it doesn't exist
          sudo mkdir -p /usr/local/bin
          
          # Download the latest Docker Scout release (v1.16.1)
          curl -sSL https://github.com/docker/scout-cli/releases/download/v1.16.1/docker-scout_1.16.1_linux_amd64.tar.gz -o /tmp/docker-scout.tar.gz
          
          # Extract the scout binary to /usr/local/bin
          sudo tar -xzf /tmp/docker-scout.tar.gz -C /usr/local/bin
          
          # List the files in /usr/local/bin to verify that the scout binary is extracted
          sudo ls -alh /usr/local/bin
          
          # Ensure that the binary is executable
          sudo chmod +x /usr/local/bin/scout

      - name: Pull and Scan Docker Image
        run: |
          # Run the scout quickscan command and output results in SARIF format
          scout quickscan nginx:latest --format sarif > scan-results.sarif

      - name: Upload Scan Results as SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scan-results.sarif
          name: docker-scan-results
